### ISSUE TITLE
服务里使用rabbitmq，始终无法注入RabbitTemplate

### ISSUE THREAD

**Issue by abings** [zuihou/zuihou-admin-cloud#13]
你好，我买了文档，在使用中做了一个服务，但是在使用rabbitmq时候，始终无法注入RabbitTemplate，你说的要排除 ‘需要自行排除 spring-cloud-starter-openfeign , 并手动引入该jar ’没明白什么意思？没有包冲突啊

**Comment by zuihou** [comment]
rabbitmq.yml 中的zhihou.rabbitmq.enabled设置成true

**Comment by abings** [comment]
谢谢回复，我已经设置了的，我看了你ScanConfiguration里面的逻辑，是做了处理的，但是依然在服务里无法注入，你不妨在demo里加个列子试下。谢谢

**Comment by zuihou** [comment]
> 谢谢回复，我已经设置了的，我看了你ScanConfiguration里面的逻辑，是做了处理的，但是依然在服务里无法注入，你不妨在demo里加个列子试下。谢谢

![image](https://user-images.githubusercontent.com/8500410/75141882-dad82f80-572c-11ea-89e0-084a493e991e.png)

修改如下：
1，nacos中的rabbitmq.yml 中的zhihou.rabbitmq.enabled设置成true
```
zuihou:
  rabbitmq:
    enabled: true
```
2，代码:
```

    @Autowired
    private RabbitTemplate rabbitTemplate;

    @GetMapping("/test")
    public R<Object> test() {
        rabbitTemplate.convertAndSend("aaa", "aaaa");
        return R.success("aa");
    }

    @Bean
    public Queue apiResourceQueue() {
        Queue queue = new Queue("aaa");
        return queue;
    }
    @RabbitListener(queues = "aaa")
    public void ScanApiResourceQueue(@Payload String param) {
        log.info(param);
    }

```
