### ISSUE TITLE
部署lamp-web-pro出错，界面不出来

### ISSUE THREAD

**Issue by victoirechan** [zuihou/zuihou-admin-cloud#147]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：4.6.1
MySQL(必填)： 5.7.9
Nacos(必填)：2.1.0

# 问题描述：
部署lamp-web-pro出错，界面不出来，一直在转圈圈，按F12，出现提示：
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/plain". Strict MIME type checking is enforced for module scripts per HTML spec.

# 报错截图
![image](https://user-images.githubusercontent.com/17776370/171403682-872dcc30-2bdb-4383-b7c4-6af972410434.png)

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
nginx没配置对

**Comment by victoirechan** [comment]
user root;
worker_processes auto;
pid /run/nginx.pid;
include /etc/nginx/modules‐enabled/*.conf;
events {
worker_connections 768;
}
http {
	server {
			listen 80;
			listen [::]:80;
			server_name 172.16.10.173;
	# /lamp-web-pro 代理前端	
		location / {
			proxy_set_header Host $host:$server_port;
			proxy_redirect off;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_connect_timeout 60;
			proxy_read_timeout 600;
			proxy_send_timeout 600;
			root /data/html/webapp;
			index index.html;
			}
	# lamp-cloud 网关服务 代理		
	location /api {
			proxy_set_header Host $host:$server_port;
			proxy_redirect off;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_connect_timeout 60;
			proxy_read_timeout 600;
			proxy_send_timeout 600;
         # 这里代理的地址一定是 lamp-cloud 项目的 lamp-gateway 服务的请求地址
			proxy_pass http://localhost:18760/api;
			}

    # Load configuration files for the default server block.
    include /etc/nginx/default.d/*.conf;

    error_page 404 /404.html;
        location = /404.html 
		{
        }

    error_page 500 502 503 504 /50x.html;
        location = /50x.html 
		{
		}
	}
}

**Comment by victoirechan** [comment]
user root;
worker_processes auto;

pid /run/nginx.pid;
include /etc/nginx/modules‐enabled/*.conf;

events {
		worker_connections 1024;
	}

http {

##
# Logging Settings
##
#access_log /home/logs/nginx/access.log;
#error_log /home/logs/nginx/error.log;

	server 
	{
			listen 80;
			listen [::]:80;
			server_name 172.16.10.173;
	# html目录
	#		root /data/html/webapp;

# 业务工程【scp‐common】请求转到网关处理
	# /lamp-web-pro 代理前端	
		location / {
			root /data/html/webapp;
			index index.html;
		}
			
	# lamp-cloud 网关服务 代理		
	location /api {
			proxy_set_header Host $host:$server_port;
			proxy_redirect off;
			proxy_set_header X-Real-IP $remote_addr;
			proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
			proxy_connect_timeout 60;
			proxy_read_timeout 600;
			proxy_send_timeout 600;
			# 这里代理的地址一定是 lamp-cloud 项目的 lamp-gateway 服务的请求地址
			proxy_pass http://localhost:18760/api;
		}
			
	location /gateway/{
			proxy_set_header X‐Real‐IP $remote_addr;
			proxy_set_header X‐Forwarded‐For $proxy_add_x_forwarded_for;
			proxy_set_header Host $http_host;
			proxy_set_header X‐NginX‐Proxy true;
			proxy_pass http://127.0.0.1:18760/;
			proxy_redirect off;
		}
	
	location /nacos{
			proxy_set_header X‐Real‐IP $remote_addr;
			proxy_set_header X‐Forwarded‐For $proxy_add_x_forwarded_for;
			proxy_set_header Host $http_host;
			proxy_set_header X‐NginX‐Proxy true;
			proxy_pass http://127.0.0.1:8848/nacos;
			proxy_redirect http://api.figetech.com/nacos http://127.0.0.1:8848/nacos;
		}

	location /rabbitmq/{
			proxy_set_header X‐Real‐IP $remote_addr;
			proxy_set_header X‐Forwarded‐For $proxy_add_x_forwarded_for;
			proxy_set_header Host $http_host;
			proxy_set_header X‐NginX‐Proxy true;
			proxy_pass http://127.0.0.1:15672/;
			proxy_redirect off;
		}	

    error_page 404 /404.html;
        location = /404.html 
		{
		}

    error_page 500 502 503 504 /50x.html;
        location = /50x.html 
		{
		}
		
	}
}
这样配置也不行。很晕
