### ISSUE TITLE
自定义数据源，网关启动报错

### ISSUE THREAD

**Issue by acuier** [zuihou/zuihou-admin-cloud#24]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：
1.2.1

# 问题描述：
网关服务，启动有问题。有远程数据源的多个租户，启动有问题

# 报错截图
本地数据源
![image](https://user-images.githubusercontent.com/10820740/92425271-507f8680-f1b9-11ea-919b-1fb6aa308acb.png)

远程数据源

![image](https://user-images.githubusercontent.com/10820740/92425272-51181d00-f1b9-11ea-8411-24c5fa6d62b5.png)

![image](https://user-images.githubusercontent.com/10820740/92425399-ba982b80-f1b9-11ea-8087-6a95c49787c3.png)

# 重现步骤
1、新建租户，初始化本地数据源，正常。2、新增租户，初始化为远程数据源，启动报错。因为分库，表不存在于default了。

**Comment by zuihou** [comment]
已修复
