### ISSUE TITLE
演示网址进不去

### ISSUE THREAD

**Issue by chaiduolai** [zuihou/zuihou-admin-cloud#32]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：
我在进入演示网址的时候一直请求超时

# 报错截图

![image](https://user-images.githubusercontent.com/45263891/96555716-b0a23600-12ea-11eb-8799-4bbc8294d5da.png)

# 重现步骤

**Comment by zuihou** [comment]
已恢复
