### ISSUE TITLE
前端请求接口被缓存

### ISSUE THREAD

**Issue by yzbgyq** [zuihou/zuihou-admin-cloud#336]
# 重现步骤

1. 列表表格有一个详情的接口，比如查看详情请求接口，第一次会请求接口，后面怎么都不会请求，应该是某个地方判断了两次点击接口一直所以第二次不会请求，我想请问怎么取消这个缓存机制

**Comment by zuihou** [comment]
上代码

**Comment by zuihou** [comment]
某些页面，在onMounted方法调用的只会触发一次，前端有缓存

**Comment by yzbgyq** [comment]
> 某些页面，在onMounted方法调用的只会触发一次，前端有缓存

不是onMounted，是点击按钮，我截个图吧
![ba9f7d9c23fa9252213c06c81074a54](https://github.com/dromara/lamp-cloud/assets/32931212/1cfb5c7d-01ac-41f0-a652-8453497779da)

**Comment by zuihou** [comment]
没代码就自己研究

**Comment by yzbgyq** [comment]
> 没代码就自己研究

什么垃圾玩意，问题我已经说的很清楚了，我要是能自己找到代码还来问你
