### ISSUE TITLE
lamp-boot 开源文档里的配置内容没找到

### ISSUE THREAD

**Issue by zqb666** [zuihou/zuihou-admin-cloud#341]
https://tangyh.top/4.19.0/opendoc/start/boot/%E5%90%8E%E7%AB%AF%E5%90%AF%E5%8A%A8.html
开源文档里

<img width="1139" alt="image" src="https://github.com/dromara/lamp-cloud/assets/6092525/a1d8fd51-b036-4096-8562-f9f1aa319fb2">
没找到红框内容的配置 是需要额外配置还是？

**Comment by zuihou** [comment]
https://tangyh.top/4.19.0/doc/start/boot/%E5%90%8E%E7%AB%AF%E5%90%AF%E5%8A%A8.html 

看这个，差不多。 开源版文档忘记更新了

**Comment by zqb666** [comment]
好的
