### ISSUE TITLE
lamp-boot 无租户版本 驱动名称问题

### ISSUE THREAD

**Issue by zqb666** [zuihou/zuihou-admin-cloud#342]
<img width="941" alt="image" src="https://github.com/dromara/lamp-cloud/assets/6092525/5dbdafa6-fd62-417f-8b34-734af30688ec">
这个 确定不是 改错了吗

**Comment by zuihou** [comment]
https://mvnrepository.com/artifact/com.mysql/mysql-connector-j

没错
