### ISSUE TITLE
lamp-web 非租户模式 启动报错

### ISSUE THREAD

**Issue by zqb666** [zuihou/zuihou-admin-cloud#343]
报错内容：Unsupported engine: wanted: {"node":"> 16.18.0"} (current: {"node":"v16.13.1","pnpm":"7.9.5"})

<img width="948" alt="image" src="https://github.com/dromara/lamp-cloud/assets/6092525/baab9053-d946-4b59-8035-b15008e8fca9">

报错如图 启动命令：pnpm dev:none
本地node 版本 v16.13.1

**Comment by zuihou** [comment]
<img width="1665" alt="image" src="https://github.com/dromara/lamp-cloud/assets/8500410/6b4fe73c-e415-45fc-b9a3-d4b0214ef668">

**Comment by zqb666** [comment]
> <img alt="image" width="1665" src="https://private-user-images.githubusercontent.com/8500410/342265831-6b4fe73c-e415-45fc-b9a3-d4b0214ef668.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkyMTkwOTYsIm5iZiI6MTcxOTIxODc5NiwicGF0aCI6Ii84NTAwNDEwLzM0MjI2NTgzMS02YjRmZTczYy1lNDE1LTQ1ZmMtYjlhMy1kNGIwMjE0ZWY2NjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYyNCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MjRUMDg0NjM2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ZTZlNzFmNGJhMTFjMzliMDJmYzIyOGI1MTE2N2VmZDZmMWIxZGU0YTRiMTExYWI0ZTU3OTczM2Q1YjRmNWI4YyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dx0VI1bJ5PxU4aGGXXq_HC70xL3D3lolwofkp1H6IyI">

版本问题升级node解决了 ，现在执行这个 报这个错是什么原因啊？
<img width="558" alt="image" src="https://github.com/dromara/lamp-cloud/assets/6092525/b1acd954-f39a-4a53-96f5-a835c79df64d">

**Comment by zuihou** [comment]
用 pnpm dev 也可
