### ISSUE TITLE
员工维护-邀请用户报错

### ISSUE THREAD

**Issue by zqb666** [zuihou/zuihou-admin-cloud#346]
<img width="1184" alt="image" src="https://github.com/dromara/lamp-cloud/assets/6092525/5bb21a34-5958-4882-b9c3-8e05e9994ec9">

后台报错 ：
<img width="817" alt="image" src="https://github.com/dromara/lamp-cloud/assets/6092525/a9f0d22d-6739-4898-9d3c-ce79965f1e15">

我在 后台baseEmployee controller里根本没看到invitationUser这个方法 上还没有提交上来嘛？
lamp-boot jdk17版本

**Comment by zuihou** [comment]
开源版没 这个功能，删除按钮就行

**Comment by zqb666** [comment]
> 开源版没 这个功能，删除按钮就行

那我是不是没法把已有的用户添加过来了？ 那用户那边 怎么给某个用户分配权限啊 没看到操作的地方？

**Comment by zuihou** [comment]
非租户版本， 用户和员工是1对1的关系。 代码是从租户版本挪过来的。   

在非租户版本里面，将用户维护页面的新增操作屏蔽就行了。  在员工页面，新增员工会自动创建用户

**Comment by zqb666** [comment]
> 非租户版本， 用户和员工是1对1的关系。 代码是从租户版本挪过来的。
> 
> 在非租户版本里面，将用户维护页面的新增操作屏蔽就行了。 在员工页面，新增员工会自动创建用户

了解了

**Comment by ixycej12** [comment]
客户注册用户没法绑定
