### ISSUE TITLE
为啥我启动项目显示我数据库url链接不了  nacos启动了配置文件看着也没问题

### ISSUE THREAD

**Issue by bpg12333** [zuihou/zuihou-admin-cloud#349]
# 前提

在 [ ]  中间输入 x, 就表示勾选该项
- [x]  举个栗子

**️ 提问之前，请检查以下列表，如果忽略此问题模板，您的问题将直接关闭！**

- [x] 确保已经将文档clone到本地，并使用Markdown工具阅读了全文 [在线文档](https://tangyh.top/opendoc/%E7%AE%80%E4%BB%8B.html)
- [x] 确保你的代码是最新版本 或 下载最新版本代码能复现
- [x] 确保已经在 [issues](https://github.com/zuihou/lamp-cloud/issues)、 [discussions](https://github.com/zuihou/lamp-cloud/discussions) 、[google](https://google.com) 查找了相关问题

# 版本信息：

- JDK 版本(包括小版本号)(必填) :
  - [ ] 8.x
  - [ ] 11.x
  - [x] 17.x
  - [ ] 其他 （____________）
- 项目模式(必填)：
  - [x] lamp-cloud
  - [ ] lamp-boot

- 源码版本(必填)：
  - [x] 4.?.?
  - [ ] 3.?.?

- MySQL(必填)：
  - [x] mysql 5.7.x
  - [ ] mysql 8.x.x
  - [ ] 其他 （____________）

- Nacos(必填)： ____________

# 问题描述：
提示： 遇到问题时，请先按以下步骤寻找答案：
- 请先尝试阅读 [文档](https://tangyh.top/opendoc/%E7%AE%80%E4%BB%8B.html)
- 请下载作者提供的最新代码或指定分支的代码到本地，启动看看是否遇到同样的问题。以排除是作者代码的问题，还是你们项目上修改产生的问题
- 问题描述步骤尽可能详细，想象一下，你们公司同事给你提问题时，你看不懂提的问题是什么心情?

按照上述步骤排查后，仍然无法解决，请写出你的问题，作者会尽可能的帮助你：

# 报错日志
```
在这里粘贴日志，方便查看
```

# 报错截图

# 重现步骤

1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by bpg12333** [comment]
Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

**Comment by zuihou** [comment]
看着文档，一步一步来

https://tangyh.top/opendoc/start/%E9%A1%B9%E7%9B%AE%E5%AF%BC%E5%85%A5.html

**Comment by bpg12333** [comment]
谢谢已经处理了
