### ISSUE TITLE
org.apache.ibatis.binding.BindingException: Invalid bound statement (not found): top.tangyh.lamp.base.mapper.ignore.BaseEmployeeIgnoreMapper.listEmployeeByUserId

### ISSUE THREAD

**Issue by shangguanbaojun** [zuihou/zuihou-admin-cloud#354]
# mybatis报错
启动项目后，登录的时候，报错
#报错截图
![报错](https://github.com/user-attachments/assets/634ed561-63e0-4f17-b47f-bc0e2c4b7844)
![登录](https://github.com/user-attachments/assets/1f929973-48c6-4b18-a507-49e5557edd42)

#已尝试办法
maven编译，项目编译，开发工具清理缓存。

**Comment by zuihou** [comment]
那个项目，什么分支，什么版本 说清楚

**Comment by zuihou** [comment]
<img width="1372" alt="image" src="https://github.com/user-attachments/assets/ed524ba5-9704-4aad-ba3a-d4f23b0681ba">
改代码了没，  改代码了，就可能是这里改错了。

**Comment by supf1995** [comment]
lamp-column-max
java17/5.x 分支
5.8.0 版本
遇到了相同的问题

**Comment by supf1995** [comment]
@zuihou
