### ISSUE TITLE
5.x赞助版跨模块调用失败

### ISSUE THREAD

**Issue by shangguanbaojun** [zuihou/zuihou-admin-cloud#358]
新创建了device服务。
里面有品牌型号和厂商

`    @Schema(description = "型号")
    @Echo(api = EchoApi.DEVICE_MODEL_ID_CLASS)
    private Long modelId;

    @Schema(description = "厂商")
    @Echo(api = EchoApi.COMPANY_ID_FEIGN_CLASS)
    private Long manufacturerId;`
    
    
![image](https://github.com/user-attachments/assets/1d8a5a80-db07-485d-9e64-6cb05c3f2416)

型号的实现类和devcie在一个模块中，可以正常回显。厂商的相关代码放在了service服务中，不能回显。
以下是service服务中的厂商(表名：company)中的Facade代码
cloud-impl中的代码
![image](https://github.com/user-attachments/assets/7a640b69-812c-4f48-a75d-64fd0ec84bfb)

![image](https://github.com/user-attachments/assets/e4b7623a-ea75-4436-85d1-20587975fae1)

boot-impl中的代码
![image](https://github.com/user-attachments/assets/db4fda0a-1401-4425-81e7-ecf077cd00f0)

![image](https://github.com/user-attachments/assets/86c59ebf-f5dc-4789-826d-d165b4b9deba)

**Comment by zuihou** [comment]
比如： 

在lamp-base服务想要回显 lamp-system服务的数据。

1. 在lamp-base-biz 加入依赖
```
        <dependency>
            <groupId>top.tangyh.lamp</groupId>
            <artifactId>lamp-system-api</artifactId>
            <version>${lamp-project.version}</version>
        </dependency>
```
2. 在lamp-base-server 加入依赖
```
      <dependency>
            <groupId>top.tangyh.lamp</groupId>
            <artifactId>lamp-system-cloud-impl</artifactId>
            <version>${lamp-project.version}</version>
        </dependency>
```
3. 其他代码参考： 
<img width="946" alt="image" src="https://github.com/user-attachments/assets/7c79a008-2320-4a6b-b145-d26bf3c33905">

**Comment by shangguanbaojun** [comment]
1、**按照您的意见，已经可以进入到FacadeImpl和Facade中的api中。但是走到api中，无法进入EchoController,出现404异常**
![image](https://github.com/user-attachments/assets/acc69eca-0d4c-4b73-ba0a-47603f88f957)
![image](https://github.com/user-attachments/assets/8de1ba9a-cf6c-41af-a944-8a43aba7e5c7)

2、**Facade中的代码完全参照DefUser中的代码写的**
![image](https://github.com/user-attachments/assets/c9ecafcb-4135-4e6d-b979-7b5a29cac523)

3、**BzCompanyApi中的代码和DefUser中的代码一样**
![image](https://github.com/user-attachments/assets/d1bb4b47-a51b-4bdf-81e3-db94ba76d164)
![image](https://github.com/user-attachments/assets/5715ce22-43bb-4426-80c9-b7768834a2fd)

4、**EchoController中的代码**
![image](https://github.com/user-attachments/assets/0078a99e-649d-4c2c-b352-da75cfece730)

**Comment by shangguanbaojun** [comment]
> 比如：
> 
> 在lamp-base服务想要回显 lamp-system服务的数据。
> 
> 1. 在lamp-base-biz 加入依赖
> 
> ```
>         <dependency>
>             <groupId>top.tangyh.lamp</groupId>
>             <artifactId>lamp-system-api</artifactId>
>             <version>${lamp-project.version}</version>
>         </dependency>
> ```
> 
> 2. 在 lamp-base-server 加入依赖
> 
> ```
>       <dependency>
>             <groupId>top.tangyh.lamp</groupId>
>             <artifactId>lamp-system-cloud-impl</artifactId>
>             <version>${lamp-project.version}</version>
>         </dependency>
> ```
> 
> 3. 其他代码参考：
> 
> <img alt="图像" width="946" src="https://private-user-images.githubusercontent.com/8500410/380373436-7c79a008-2320-4a6b-b145-d26bf3c33905.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAwOTgzNzksIm5iZiI6MTczMDA5ODA3OSwicGF0aCI6Ii84NTAwNDEwLzM4MDM3MzQzNi03Yzc5YTAwOC0yMzIwLTRhNmItYjE0NS1kMjZiZjNjMzM5MDUucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTAyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEwMjhUMDY0NzU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODY1MTAyMjBkMzE5MDc0NWJiMzZlYzNhNmQ0Y2Q3NTYxZTlkMWMyNzBhZWY4NTBiYmEwNjFjYTM1M2QyZTEzYSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.mf5cjwwyE9T6aXSJpiqtRrcMlMYQOnlr51cxe7f5i0g">



1、**按照您的意见，已经可以进入到FacadeImpl中，但无法调用Facade中的api。报异常，如下：**
![image](https://github.com/user-attachments/assets/2e0e5842-e6ed-46ef-a9fd-1c1cf3b01a53)


2、**Facade中的代码完全参照DefUser中的代码写的**
![image](https://github.com/user-attachments/assets/c9ecafcb-4135-4e6d-b979-7b5a29cac523)

3、**BzCompanyApi中的代码和DefUser中的代码一样**
![image](https://github.com/user-attachments/assets/d1bb4b47-a51b-4bdf-81e3-db94ba76d164)
![image](https://github.com/user-attachments/assets/5715ce22-43bb-4426-80c9-b7768834a2fd)

4、**EchoController中的代码**
![image](https://github.com/user-attachments/assets/0078a99e-649d-4c2c-b352-da75cfece730)

**Comment by zuihou** [comment]
1. BzCompanyApi 类上的注解理解一下：
```
// name 属性表示， 给类里面的接口要调用哪个服务？
@FeignClient(name = "${" + Constants.PROJECT_PREFIX + ".feign.system-server:lamp-system-server}")
```

你的接口里面指定了 lamp-system-server服务

2. 所以需要再system服务里面去写实现类，而不是oauth服务
你截图里面，EchoController 存放在oauth服务，必然是无法调用成功的。

**Comment by shangguanbaojun** [comment]
> 1. BzCompanyApi 类上的注解理解一下：
> 
> ```
> // name 属性表示， 给类里面的接口要调用哪个服务？
> @FeignClient(name = "${" + Constants.PROJECT_PREFIX + ".feign.system-server:lamp-system-server}")
> ```
> 
> 你的接口里面指定了 lamp-system-server服务
> 
> 2. 所以需要再system服务里面去写实现类，而不是oauth服务
>    你截图里面，EchoController 存放在oauth服务，必然是无法调用成功的。

哎呀，真的是，我刚弄好，上来打算关掉问题，然后看到你的回复了。谢谢你哈。
