### ISSUE TITLE
默认的三个header参数值可以一直不登录访问接口吗？

### ISSUE THREAD

**Issue by zqb666** [zuihou/zuihou-admin-cloud#359]
<img width="916" alt="image" src="https://github.com/user-attachments/assets/2823a76e-8cea-4203-8fbe-3e8d1484a0e3">

这三个

**Comment by zuihou** [comment]
在集成sa-token之前的版本中，在本地(dev环境)启动项目时，为了方便开发人员测试，将Token=test标记为特殊Token可以一直使用。  在prod环境，无效。


集成sa-token后，Token必须正确传递，才行。
