### ISSUE TITLE
lamp-boot项目，我有几个后端接口，想给移动端调用，如何去掉登录验证和权限验证？

### ISSUE THREAD

**Issue by zqb666** [zuihou/zuihou-admin-cloud#360]
lamp-boot项目，我有几个后端接口，想给移动端调用，如何去掉登录验证和权限验证？

**Comment by zuihou** [comment]
看懂 AuthenticationSaInterceptor 或者 AuthenticationFilter 拦截器（前者是5.x版本，否则是4.x版本） 的拦截规则， 按照自己的思路修改这个拦截器或者配置文件，使得你的接口跳过这个拦截器。

**Comment by zqb666** [comment]
> 看懂 AuthenticationSaInterceptor 或者 AuthenticationFilter 拦截器（前者是5.x版本，否则是4.x版本） 的拦截规则， 按照自己的思路修改这个拦截器或者配置文件，使得你的接口跳过这个拦截器。

<img width="726" alt="image" src="https://github.com/user-attachments/assets/534486c0-cf15-4c71-b696-24173ae919fc">
zhe'li这里配置了 需要放行的接口通配符地址应该就行了吧？

**Comment by zuihou** [comment]
还有： TokenContextFilter 类， 负责解析或忽略 租户ID， 解析或忽略Token （token就决定是否登录）。

AuthenticationSaInterceptor 或者 AuthenticationFilter ，负责验证uri权限。
