### ISSUE TITLE
5.0代码生成器生成项目，本地生成报错，提示：文件不存在

### ISSUE THREAD

**Issue by kevinhwq** [zuihou/zuihou-admin-cloud#365]
# 前提

在 [ ]  中间输入 x, 就表示勾选该项
- [x]  举个栗子

**️ 提问之前，请检查以下列表，如果忽略此问题模板，您的问题将直接关闭！**

- [x] 确保已经将文档clone到本地，并使用Markdown工具阅读了全文 [在线文档](https://tangyh.top/opendoc/%E7%AE%80%E4%BB%8B.html)
- [x] 确保你的代码是最新版本 或 下载最新版本代码能复现
- [x] 确保已经在 [issues](https://github.com/zuihou/lamp-cloud/issues)、 [discussions](https://github.com/zuihou/lamp-cloud/discussions) 、[google](https://google.com) 查找了相关问题

# 版本信息：

- JDK 版本(包括小版本号)(必填) :
  - [ ] 8.x
  - [ ] 11.x
  - [x] 17.x
  - [ ] 其他 （____________）
- 项目模式(必填)：
  - [ ] lamp-none
  - [ ] lamp-none-flex
  - [ x] lamp-column
- 源码版本(必填)：
  - [x] 5.0.3
  - [ ] 4.?.?
  - [ ] 3.?.?

- MySQL(必填)：
  - [ ] mysql 5.7.x
  - [x] mysql 8.x.x
  - [ ] 其他 （____________）

- Nacos(必填)： __无__________

# 问题描述：
提示： 遇到问题时，请先按以下步骤寻找答案：
- 请先尝试阅读 [文档](https://tangyh.top/opendoc/%E7%AE%80%E4%BB%8B.html)
- 请下载作者提供的最新代码或指定分支的代码到本地，启动看看是否遇到同样的问题。以排除是作者代码的问题，还是你们项目上修改产生的问题
- 问题描述步骤尽可能详细，想象一下，你们公司同事给你提问题时，你看不懂提的问题是什么心情?

按照上述步骤排查后，仍然无法解决，请写出你的问题，作者会尽可能的帮助你：

# 报错日志
```
后台无报错日志
```

# 报错截图
![image](https://github.com/user-attachments/assets/5ebb288b-d74f-4472-b125-731f931a56c2)

# 重现步骤
1、开发者管理》开发工具》项目生成
2、生成路径填写：/Users/xxxxx/lamp-column-max
3、点击本地生成
4、提示错误
5、已生成项目文件，但是这些操作未完成：
<img width="662" alt="image" src="https://github.com/user-attachments/assets/3582b2fe-15d3-42d6-b1fa-ff68444bdb0b">

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
1. 单体模式还是微服务模式启动？
2. 本地idea启动还是 采用jar方式部署在服务器上？

**Comment by zuihou** [comment]
http://git.tangyh.top/zuihou/lamp-column-max/commit/03ba1decf60bc0011be2c28baa5f4df876bc03e2


已修复
