### ISSUE TITLE
单体模式下启动，控制台打印的naos地址不正确

### ISSUE THREAD

**Issue by yangdecai** [zuihou/zuihou-admin-cloud#368]
# 前提

在 [ ]  中间输入 x, 就表示勾选该项
- [x]  举个栗子

**️ 提问之前，请检查以下列表，如果忽略此问题模板，您的问题将直接关闭！**

- [ ] 确保已经将文档clone到本地，并使用Markdown工具阅读了全文 [在线文档](https://tangyh.top/opendoc/%E7%AE%80%E4%BB%8B.html)
- [ ] 确保你的代码是最新版本 或 下载最新版本代码能复现
- [ ] 确保已经在 [issues](https://github.com/zuihou/lamp-cloud/issues)、 [discussions](https://github.com/zuihou/lamp-cloud/discussions) 、[google](https://google.com) 查找了相关问题

# 版本信息：

- JDK 版本(包括小版本号)(必填) :
  - [ ] 8.x
  - [ ] 11.x
  - [x] 17.x
  - [ ] 其他 （____________）
- 项目模式(必填)：
  - [x] lamp-datasource-max
  - [ ] lamp-none-flex

- 源码版本(必填)：
  - [x] 5.0.4
  - [ ] 3.?.?

- MySQL(必填)：
  - [ ] mysql 5.7.x
  - [x] mysql 8.x.x
  - [ ] 其他 （____________）

- Nacos(必填)： 2.4.3

# 问题描述：
提示： 遇到问题时，请先按以下步骤寻找答案：
- 请先尝试阅读 [文档](https://tangyh.top/opendoc/%E7%AE%80%E4%BB%8B.html)
- 请下载作者提供的最新代码或指定分支的代码到本地，启动看看是否遇到同样的问题。以排除是作者代码的问题，还是你们项目上修改产生的问题
- 问题描述步骤尽可能详细，想象一下，你们公司同事给你提问题时，你看不懂提的问题是什么心情?

按照上述步骤排查后，仍然无法解决，请写出你的问题，作者会尽可能的帮助你：
单体模式下启动，控制台打印的naos地址不正确，相应的变量没有被替换掉
nacos访问地址(单体版请忽略): http://${lamp.nacos.ip}:${lamp.nacos.port}/nacos    nacos命名空间: ${lamp.nacos.namespace}

# 报错日志
```


  ,--,                         ____
,--.'|                       ,'  , `.,-.----.
|  | :                    ,-+-,.' _ |\    /  \
:  : '                 ,-+-. ;   , |||   :    |
|  ' |     ,--.--.    ,--.'|'   |  |||   | .\ :
'  | |    /       \  |   |  ,', |  |,.   : |: |
|  | :   .--.  .-. | |   | /  | |--' |   |  \ :
'  : |__  \__\/: . . |   : |  | ,    |   : .  |
|  | '.'| ," .--.; | |   : |  |/     :     |`-'
;  :    ;/  /  ,.  | |   | |`-'      :   : :
|  ,   /;  :   .'   \|   ;/          |   | :
 ---`-' |  ,     .-./'---'           `---'.|
         `--`---'                      `---`

Spring Boot Version: 3.3.6
当前服务: lamp-boot-server-datasource   激活环境: dev   当前版本: 5.0.4
nacos访问地址(单体版请忽略): http://${lamp.nacos.ip}:${lamp.nacos.port}/nacos    nacos命名空间: ${lamp.nacos.namespace}
版权和最终解释权归 ©最后(https://github.com/zuihou) 所有
如果此项目的任何一部分对你有所帮助，恳请你为该项目点个Star，以表支持：https://github.com/dromara/lamp-cloud
```

# 报错截图
<img width="1112" alt="1735286895405" src="https://github.com/user-attachments/assets/276a3de6-cc49-4da3-98a8-e83f01776519" />

# 重现步骤
单体版，开启分布式事务,isSeata： true，然后启动项目
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by zuihou** [comment]
是这样的，因为单体和微服务共用一个 banner文件。

但单体版没有使用nacos，所以就读不到参数。 

单体版就不用管这行了
