### ISSUE TITLE
gateway启动出错

### ISSUE THREAD

**Issue by zgcxyz183** [zuihou/zuihou-admin-cloud#39]
用了最新2.7.0   
RedisAutoConfigure 67行去掉@ConditionalOnMissingBean 就没问题了
不去掉就会报错
***************************
APPLICATION FAILED TO START
***************************

Description:

Parameter 0 of method RedisDistributedLock in com.github.zuihou.cache.RedisAutoConfigure required a bean of type 'org.springframework.data.redis.core.RedisTemplate' that could not be found.

The following candidates were found but could not be injected:
	- Bean method 'redisTemplate' in 'RedisAutoConfigure' not loaded because @ConditionalOnMissingBean (types: org.springframework.data.redis.core.RedisTemplate; SearchStrategy: all) found beans of type 'org.springframework.data.redis.core.RedisTemplate' redisTemplate, stringRedisTemplate

Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.data.redis.core.RedisTemplate' in your configuration.

**Comment by zuihou** [comment]
更新代码
