### ISSUE TITLE
src/main/filters 配置环境动态切换 这边是怎么操作的

### ISSUE THREAD

**Issue by yangyz** [zuihou/zuihou-admin-cloud#42]
# 版本信息：
JDK 版本(必填) : 1.8.0
源码版本(必填)：
MySQL(必填)： 5.7.9
Nacos(必填)：

# 问题描述：
![image](https://user-images.githubusercontent.com/6257884/100495720-4605d500-3189-11eb-8e16-a981a2decbe1.png)

动态切换 dev 与 prod

# 报错截图

# 重现步骤
1. 访问了什么接口？
2. 传递什么参数？
3. 后端控制台报了什么错？
4. 前端控制台报了什么错？

# 支持一下
如果该issue帮助了你, 麻烦给项目点个star, 并给当前issue回复一下 “👍” 或者 “已解决”.

**Comment by yangyz** [comment]
![image](https://user-images.githubusercontent.com/6257884/100495886-a3e6ec80-318a-11eb-8d45-8e6217208d66.png)

**Comment by zuihou** [comment]
1. zuihou-xxx-server/pom.xml 里面配置了: 
```
<filters>
            <filter>../../src/main/filters/config-${profile.active}.properties</filter>
        </filters>
```
2. zuihou-admin-cloud/pom.xml 里面配置了: 
```
 <profiles>
        <!-- 开发环境 -->
        <profile>
            <id>dev</id>
            <properties>
                <profile.active>dev</profile.active>
            </properties>
            <activation>
                <activeByDefault>true</activeByDefault>
            </activation>
        </profile>
        <!-- 生产环境-->
        <profile>
            <id>prod</id>
            <properties>
                <profile.active>prod</profile.active>
            </properties>
        </profile>
    </profiles>
```

3. 然后参考这个:  https://github.com/zuihou/zuihou-admin-cloud/issues/28

**Comment by zuihou** [comment]
如何切换? 

打包编译时传递参数:
```
mvn   clean package -Pdev

mvn   clean package -Pprod
```

**Comment by yangyz** [comment]
谢谢
