### ISSUE TITLE
Web页面有必要和我的弄成一样么？

### ISSUE THREAD

**Issue by wuyouzhuguli** [zuihou/zuihou-admin-cloud#7]
http://tangyh.top:10000/zuihou-ui/#/login

https://cloud.mrbird.cn/

同为开源爱好者，如果你喜欢我的前端界面，你可以借鉴，但至少得留下出处吧？

**Comment by zuihou** [comment]
已加出处，以后多交流~ /::)

**Comment by wuyouzhuguli** [comment]
👍
